---
name: JUnit Test Suite
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
jobs:
  run-junit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven
      - name: Install dependencies
        run: mvn install -DskipTests

      - name: Run tests
        run: mvn test

      # - name: Run Integration Script
      #   run: bash .github/workflows/integration.sh -t ${{ secrets.PARTICLE_TOKEN }} -u ${{ secrets.PARTICLE_USERNAME }} -p ${{ secrets.PARTICLE_PASSWORD }}
      # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
      - name: Update dependency graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
        with:
          token: ${{ secrets.GH_TOKEN }}
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.0.1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
